In [1]:
import numpy as np

In [2]:
# making a basic 1d numpy array
array_lst = [1,2,3,4,5,6,7,8,9,0]
np_arr = np.array(array_lst)
print(type(np_arr), np_arr)

<class 'numpy.ndarray'> [1 2 3 4 5 6 7 8 9 0]


In [3]:
# Different Types of NumPy Arrays
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)  # dimensions, the fill value
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


In [4]:
# array slicing is just like string slicing
sliced_arr1 = np_arr[-7:8:1]
print(sliced_arr1)

[4 5 6 7 8]


In [5]:
# 2d array indexing
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
"""
a = 
[1, 2]
[3, 4]
[5, 6]
"""
print(a[[0 ,1 ,2 ],[0 ,1 ,1]]) # this selects [row(x),row(y),etc...], [column(x),column(y),etc...] --> together they form = (row(x),column(x)),(row(y),column(y)),etc...


[1 4 6]


In [6]:
# array shapes
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
"""
b = 
[1, 2, 3, 4]
[5, 6, 7, 8]
-> hence shape = 2 x 4
"""
print(b.shape)

(2, 4)


In [ ]:
# array reshaping
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_2d = c.reshape(3, 4) # if number of new array elemnts and old array elements dont match it will give error so (4,3) is ok but (3,3)or(4,4) will error
print(arr_2d,'\n')

# reshape from 1d to 3d
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3d = d.reshape(2, 3, 2)
print(arr_3d,'\n')

# .base function
e = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(e.reshape(2, 4).base,'\n') # this .base tells on what is the new modified array based on
print(e.reshape(2, 4),'\n') # this will output the new modified array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 

[1 2 3 4 5 6 7 8] 

[[1 2 3 4]
 [5 6 7 8]] 

