In [1]:
import numpy as np

In [2]:
# basic same dimension array addition without bradcasting

a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2,3)

b = np.array([[10, 20, 30],
              [40, 50, 60]])  # shape (2,3)

c = a + b
print(c)

[[11 22 33]
 [44 55 66]]


In [4]:
# now broadcasting
a = np.array([10, 20, 30, 40, 50]).reshape(5,1)   # shape (5,)
b = np.ones((5, 4))   # shape (5,4)
print("a shape:", a.shape)   # (5,)
print("b shape:", b.shape)   # (5,4)
print('a:',a)
print('b:',b)
c = a + b
print("c shape:", c.shape)   # (5,4)
print('c:',c)

a shape: (5, 1)
b shape: (5, 4)
a: [[10]
 [20]
 [30]
 [40]
 [50]]
b: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
c shape: (5, 4)
c: [[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]
 [41. 41. 41. 41.]
 [51. 51. 51. 51.]]


In [5]:
"""
NumPy Broadcasting Rules
	1.	Align shapes from right → left
	•	If shapes don’t have same length, pad the smaller one with 1s on the left.
	2.	Dimension compatibility
	•	✅ Dimensions are equal
	•	✅ OR one of them is 1
	•	❌ Otherwise → error
	3.	Stretch where dimension = 1
	•	NumPy repeats the data along that axis to match the bigger size.
	4.	Final output shape
	•	Take the largest size in each dimension after broadcasting.

Quick Examples
•	(5, 3) + (3,) → (5, 3)
•	(5, 1) + (5, 4) → (5, 4)
•	(1, 3) + (5, 3) → (5, 3)
•	(4, 3, 2) + (3, 1) → (4, 3, 2)
•	(2, 1) + (8, 3, 2, 1) → (8, 3, 2, 1)

Pad with 1s on the left
Compare right to left
If mismatch and no 1 → ❌ error

"""

'\nNumPy Broadcasting Rules\n\t1.\tAlign shapes from right → left\n\t•\tIf shapes don’t have same length, pad the smaller one with 1s on the left.\n\t2.\tDimension compatibility\n\t•\t✅ Dimensions are equal\n\t•\t✅ OR one of them is 1\n\t•\t❌ Otherwise → error\n\t3.\tStretch where dimension = 1\n\t•\tNumPy repeats the data along that axis to match the bigger size.\n\t4.\tFinal output shape\n\t•\tTake the largest size in each dimension after broadcasting.\n\nQuick Examples\n•\t(5, 3) + (3,) → (5, 3)\n•\t(5, 1) + (5, 4) → (5, 4)\n•\t(1, 3) + (5, 3) → (5, 3)\n•\t(4, 3, 2) + (3, 1) → (4, 3, 2)\n•\t(2, 1) + (8, 3, 2, 1) → (8, 3, 2, 1)\n\nPad with 1s on the left\nCompare right to left\nIf mismatch and no 1 → ❌ error\n\n'