In [1]:
import numpy as np

In [9]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))

# transpose of matrix A
print("\nTranpose of A:\n", np.linalg.matrix_transpose(A))
 
# matrix multiplication works like this C[0,0] = 6*6 + 1*4 + 1*2 = 36 + 4 + 2 = 42 --for this above matrix example :)
print("\nMatrix A raised to power 2:\n",
           np.linalg.matrix_power(A, 2))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Tranpose of A:
 [[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]

Matrix A raised to power 2:
 [[42 12 18]
 [26 48 29]
 [58 42 91]]


In [13]:
# dot product of scalar and vectors
product = np.dot(5, 4)
print("Dot Product of scalar values  : ", product)

vector_a = 2 + 3j
vector_b = 4 + 5j

product = np.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product of scalar values  :  20
Dot Product  :  (-7+22j)
