In [ ]:
import numpy as np

In [ ]:
# numpy 2 arrays basic ops
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = np.add(a, b)
print(add_ans)

sub_ans = np.subtract(a, b)
print(sub_ans)

multiply_ans = np.multiply(a, b)
print(multiply_ans)

div_ans = np.divide(a, b)
print(div_ans)

mod_ans = np.mod(a, b) # mod = modulus
print(mod_ans)

[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[ 1  2  3 10]


In [12]:
# mean, std. deviation, & variance
array = np.arange(10)
print(array)

r1 = np.mean(array)
print("\nMean: ", r1)

r2 = np.std(array)
print("\nstd: ", r2)

r3 = np.var(array)
print("\nvariance: ", r3)

r4 = np.sum(array)
print("\nSum: ", r4)

[0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

std:  2.8722813232690143

variance:  8.25

Sum:  45
